package com.learningcompanion.shared.audit;

public enum AuditAction {
    ACCOUNT_REGISTERED,
    REGISTRATION_ATTEMPT_EXISTING_EMAIL,
    VERIFICATION_EMAIL_SENT,
    VERIFICATION_EMAIL_RESENT,
    VERIFICATION_LINK_EXPIRED,
    EMAIL_VERIFIED,
    CONSENT_GRANTED,
    SESSION_CREATED,
    SESSION_REVOKED
}
