package com.learningcompanion.shared.audit;

public enum AuditAction {
    ACCOUNT_REGISTERED,
    REGISTRATION_ATTEMPT_EXISTING_EMAIL,
    VERIFICATION_EMAIL_SENT,
    VERIFICATION_EMAIL_RESENT,
    VERIFICATION_LINK_EXPIRED,
    EMAIL_VERIFIED,
    CONSENT_GRANTED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_LOCKED,
    NEW_DEVICE_ALERT_SENT,
    SESSION_CREATED,
    SESSION_REVOKED
}
